<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ch.so.agi</groupId>
    <artifactId>hop-plugin-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath/>
  </parent>
  <groupId>ch.so.agi</groupId>
  <artifactId>hop-geometry-inspector-plugin-parent</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>Apache Hop Geometry Inspector Plugin</name>
  <description>Desktop Geometry Inspector plugin for Apache Hop.</description>
  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/license/mit/</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <modules>
    <module>hop-geometry-inspector</module>
    <module>assemblies</module>
    <module>integration-tests</module>
  </modules>

  <properties>
    <hop.geometry.type.version>0.2.0-SNAPSHOT</hop.geometry.type.version>
    <jts.version>1.20.0</jts.version>
    <geotools.version>35.1</geotools.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.geotools</groupId>
        <artifactId>gt-bom</artifactId>
        <version>${geotools.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo1.maven.org/maven2/</url>
    </repository>
    <repository>
      <id>osgeo</id>
      <url>https://repo.osgeo.org/repository/release/</url>
    </repository>
    <repository>
      <id>sogeo-releases</id>
      <url>https://jars.interlis.guru/releases/</url>
    </repository>
    <repository>
      <id>sogeo-snapshots</id>
      <url>https://jars.interlis.guru/snapshots/</url>
    </repository>
  </repositories>

</project>
